"""changed optio_two to option_two

Revision ID: 00a5943b01a3
Revises: fb54b64a1ed0
Create Date: 2023-08-31 12:14:39.978605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a5943b01a3'
down_revision = 'fb54b64a1ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_two', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('option_two_count', sa.Integer(), nullable=True))
        batch_op.drop_column('optio_two_count')
        batch_op.drop_column('optio_two')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optio_two', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('optio_two_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('option_two_count')
        batch_op.drop_column('option_two')

    # ### end Alembic commands ###
