"""changed my Vote model to Poll and updated the properties

Revision ID: 0191b63e61bf
Revises: b676173feadb
Create Date: 2023-08-30 14:11:00.404561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0191b63e61bf'
down_revision = 'b676173feadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_one', sa.String(), nullable=False),
    sa.Column('optio_two', sa.String(), nullable=False),
    sa.Column('option_three', sa.String(), nullable=False),
    sa.Column('option_one_count', sa.Integer(), nullable=True),
    sa.Column('optio_two_count', sa.Integer(), nullable=True),
    sa.Column('option_three_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('python', sa.INTEGER(), nullable=True),
    sa.Column('php', sa.INTEGER(), nullable=True),
    sa.Column('nodejs', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('polls')
    # ### end Alembic commands ###
