"""added question to my Poll model properties

Revision ID: fb54b64a1ed0
Revises: 0191b63e61bf
Create Date: 2023-08-30 14:33:32.147150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb54b64a1ed0'
down_revision = '0191b63e61bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_column('question')

    # ### end Alembic commands ###
